# Generated by Django 2.2.3 on 2019-07-28 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='completed',
        ),
    ]
