# Generated by Django 2.2.3 on 2019-07-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_remove_list_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
