# Generated by Django 2.2.3 on 2019-08-18 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_list_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
